spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goods?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 105030
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: ccitTest-yuanky
  #mvc: 
    #throw-exception-if-no-handler-found: true              #出现错误时, 直接抛出异常
  #resources.add-mappings: false     #关闭工程中的资源文件建立映射
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:mappers/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.chinacoal.microservice.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    #logic-delete-value: 1
    #logic-not-delete-value: 0
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'

server:
  port: 8082    
    
    
logging:
  config: classpath:log4j2-spring.xml 
  file: ${spring.application.name}    
  path: ./logs 
  register-shutdown-hook: true      
  
endpoints:
  logfile:
    enabled: true
    external-file: ${logging.path}/${logging.file}-trace.log

eos:
  system-id: sys-org
  service:
    client:
      mode: feign
      http-log-level: basic
      connect-timeout: 10000
      read-timeout: 30000
    server:
      http-log-level: basic
      default-error-status: 500
    security:
      header-secrets:
      - header: X-ER-Gateway-Token
        secret-key: 30819f300d06092a864886f70d010101050003818d0030818902818100c785dc7bd944fa7c2d5c67f1f164d82ad9f9666dac622ced3f331ac5d2e52584cb2ccfa7e60f28aca07cebf1cf95971d7c6283d9b71056746a553ba318c1f21f7cb9b24a1f18311b583953f0de17d26b560239ab46768e6a043d65273f1a90599d1a9b21f8c2eff3da53854cfcbc8e82bcd7f2dab95119486c2261e9e5c38c610203010001  # configure gateway public key
      - header: X-ER-App-Token
        secret-key:  340b83d8-c7ae-48da-bc2d-d462e1d58f37

feign:
  hystrix:
    enabled: true
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
management:
  security:
    enabled: false
security:
  basic:
    enabled: false
  user:
    name: root
    password: root
  iam:
    enabled: false
    #sso:
      #host: http://172.20.8.52:9091/iam
      #enabled: false
      #logoutUrl: /logout
    #login-url: /sso-login
    #logout-url: /logout
      
  #oauth2:
    #client:
      #client-id: hTPBDDVY2xJo
      #client-secret: EZpbSDtHoxNDBG0wy7COSaYnopQosjOvmaRjJpVrEIlwAcQL
      #access-token-uri: ${security.iam.sso.host}/oauth/token # 配置access token uri 默认即可
     # user-authorization-uri: ${security.iam.sso.host}/oauth/authorize # 配置授权地址 默认即可
      #scope: default
    #resource:
      #jwt:
       # key-value: non-prod-signature
    #sso:
      #login-path: {security.iam.login-url}

    basic:
        enabled: false
    enable-csrf: false 
        